### ISSUE TITLE
Need to unregisterReceiver wifiReceiver

### ISSUE THREAD

**Issue by himangipatel** [appwise-labs/NoInternetDialog#10]
**Library is very pretty to Use** 👍

I am initialized and register for Dialog In  my BaseActivity's on create method
 
 new NoInternetDialog.Builder(this)
        .setBgGradientCenter(ContextCompat.getColor(BaseActivity.this, R.color.colorPrimary))
        .setBgGradientStart(ContextCompat.getColor(BaseActivity.this, R.color.colorPrimary))
        .setBgGradientEnd(ContextCompat.getColor(BaseActivity.this, R.color.colorPrimary))
        .setButtonColor(ContextCompat.getColor(BaseActivity.this, R.color.colorAccent))
        .build(); 

E/ActivityThread: Activity com.medeasypatient.activities.IntroAppActivity has leaked IntentReceiver am.appwise.components.ni.NetworkStatusReceiver@9088fea that was originally registered here. Are you missing a call to unregisterReceiver()?

I think there should be some method to unregister wifiReceiver method.

**Comment by robertlevonyan** [comment]
please update to version 1.1.2

**Comment by mrrohit1** [comment]
This issue is still in 1.1.3 version. Please let me know how can i unregister wifiReciever ??
