### ISSUE TITLE
Close button visibility

### ISSUE THREAD

**Issue by pratikghosalkar** [appwise-labs/NoInternetDialog#11]
1. Wifi loading and "PLEASE TURN ON" string should have some margin because while loading progress bar is little hidden under text view. Check screenshot.
![screenshot_20171220-181030](https://user-images.githubusercontent.com/8897729/34207901-5640c176-e5b2-11e7-9fce-03b5783e69b6.png)

2. Is there any callback/listener for a successful connection, so that we can do some work after connection established.

3. It's not an issue actually. It would be great if we can enable/disable close button or change its visibility so that we can have the non-cancelable dialog.

**Comment by robertlevonyan** [comment]
Hi.
Please update to version 1.1.3

Here you can find a callback for internet connection, and you can set the dialog cancelable or not.
All this you can do right from builder.
