### ISSUE TITLE
Error in gradle build in compileSdkVersion 27

### ISSUE THREAD

**Issue by gautam2682** [appwise-labs/NoInternetDialog#12]
Gradle is not building after adding 

`    implementation 'am.appwise.components:NoInternetDialog:1.1.3'
`

Log cat error is - 

> Error:Execution failed for task ':app:processDebugManifest'.
> > Manifest merger failed : Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:14:9-40
>   	is also present at [am.appwise.components:NoInternetDialog:1.1.3] AndroidManifest.xml:20:9-47 value=(@style/NoInternetTheme).
>   	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:9:5-33:19 to override.

**Comment by robertlevonyan** [comment]
Add tools:replace="android:theme" to your <application ../> in Manifest.xml

**Comment by gautam2682** [comment]
I used it but them another errors came in the application logcat

**Comment by robertlevonyan** [comment]
Can you share those errors?

**Comment by gautam2682** [comment]
> Error:(203, 46) No resource found that matches the given name (at 'layout_constraintBottom_toTopOf' with value '@id/buttons').
> Error:java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process /Users/gauti/Library/Android/sdk/build-tools/26.0.2/aapt with arguments {package -f --no-crunch -I /Users/gauti/Library/Android/sdk/platforms/android-27/android.jar -M /Users/gauti/Documents/AndroidStudioProjects/SolutionsinEnglish/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/gauti/Documents/AndroidStudioProjects/SolutionsinEnglish/app/build/intermediates/res/merged/debug -m -J /Users/gauti/Documents/AndroidStudioProjects/SolutionsinEnglish/app/build/generated/source/r/debug -F /Users/gauti/Documents/AndroidStudioProjects/SolutioninEnglish/app/build/intermediates/res/debug/resources-debug.ap_ --custom-package english.solutions -0 apk --output-text-symbols /Users/gauti/Documents/AndroidStudioProjects/NcertSolutionsinEnglish/app/build/intermediates/symbols/debug --no-version-vectors}
> Error:org.gradle.process.internal.ExecException: Process 'command '/Users/gauti/Library/Android/sdk/build-tools/26.0.2/aapt'' finished with non-zero exit value 1


After adding tools:replace="android:theme" these errors came up , your library is very good . please help.)
