### ISSUE TITLE
Reduce the size by removing unneeded fonts, images, etc

### ISSUE THREAD

**Issue by mradzinski** [appwise-labs/NoInternetDialog#2]
4mb for a dialog is way too much. You have added into library the whole Montserrat font family, still have the ic_luncher mipmaps, and plenty other stuff which is definitively not needed to use this library.

**Comment by robertlevonyan** [comment]
please udpate to v1.1.0

**Comment by mradzinski** [comment]
Just checked the branch. Mipmap folders are still there (and AFAIK libraries don't need a launcher icon), so is the whole font family which I doubt is entirely used. So is the `<string name="app_name">No Internet Dialog</string>` in Strings which is not needed at all, so is the `application` entry in the Manifest.xml which isn't needed for a library.

Please, reopen this issue until you clean all that stuff.

**Comment by robertlevonyan** [comment]
This files was removed from bintray repo, and from this github repo they are also removed. Check it again, please.
