### ISSUE TITLE
implementation error

### ISSUE THREAD

**Issue by Arunkrishna008** [appwise-labs/NoInternetDialog#22]
i get an error when iam implementing your lib in my app,

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:11:9-40
  	is also present at [am.appwise.components:NoInternetDialog:1.1.3] AndroidManifest.xml:20:9-47 value=(@style/NoInternetTheme).
  	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:5:5-13:19 to override.

**Comment by klil21** [comment]
the same here :(

**Comment by klil21** [comment]
i sloved it 
Add tools:replace="android:theme" to your <application ../> in Manifest.xml
