### ISSUE TITLE
WifiReceiver not registered

### ISSUE THREAD

**Issue by iceberg1369** [appwise-labs/NoInternetDialog#27]
I get following error when I close the activity

    java.lang.RuntimeException: Unable to destroy activity {ca.DescriptionActivity}: java.lang.IllegalArgumentException: Receiver not registered: am.appwise.components.ni.WifiReceiver@9ba12bf

**Comment by ImaginativeShohag** [comment]
You can try this similar library: https://github.com/ImaginativeShohag/Oops-No-Internet

**Comment by iceberg1369** [comment]
@ImaginativeShohag thanks
