### ISSUE TITLE
where do i instanciate the NoInternet Dialog?

### ISSUE THREAD

**Issue by loicleprogrammeur** [appwise-labs/NoInternetDialog#28]

**Comment by MarsVard** [comment]
Hi @loicleprogrammeur , you can instantiate the dialog in the onCreate() method of the  fragment or activity you want it to appear in. 

And destroy the dialog in the onDestroy() method.

**Comment by loicleprogrammeur** [comment]
l ya i did that but nothing is happening

**Comment by loicleprogrammeur** [comment]
nothing happens when i switch off the connexion

or turn un the airplane mode

Le jeu. 4 oct. 2018 à 10:52, olaa <ngapmennyamiyannickloic@gmail.com> a
écrit :

> l ya i did that but nothing is happening
>
