### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by felixeduardo15** [appwise-labs/NoInternetDialog#4]
Gradle:
` implementation 'am.appwise.components:NoInternetDialog:1.1.0'`

MainActivity:
`new NoInternetDialog.Builder(this).build();`

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/AppThemeDWClub) from AndroidManifest.xml:14:9-46
  	is also present at [am.appwise.components:NoInternetDialog:1.1.0] AndroidManifest.xml:20:9-47 value=(@style/NoInternetTheme).
  	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:7:5-57:19 to override.

**Comment by robertlevonyan** [comment]
hi you can add tools:replace="android:theme" for now. this will fix this issue
