### ISSUE TITLE
Resources not found API 19

### ISSUE THREAD

**Issue by felixeduardo15** [appwise-labs/NoInternetDialog#5]
`new NoInternetDialog.Builder(this).build();`

Error:
> android.content.res.Resources$NotFoundException: File res/drawable/ic_wifi_white.xml from drawable resource ID #0x7f07007d. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
>                                                                                 at android.content.res.Resources.loadDrawable(Resources.java:2136)
>                                                                                 at android.content.res.Resources.getDrawable(Resources.java:715)
>                                                                                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:353)
>                                                                                 at am.appwise.components.ni.NoInternetDialog.initButtonStyle(NoInternetDialog.java:275)
>                                                                                 at am.appwise.components.ni.NoInternetDialog.onCreate(NoInternetDialog.java:195)
>                                                                                 at android.app.Dialog.dispatchOnCreate(Dialog.java:396)
>                                                                                 at android.app.Dialog.show(Dialog.java:268)
>                                                                                 at am.appwise.components.ni.NoInternetDialog.show(NoInternetDialog.java:563)
>                                                                                 at am.appwise.components.ni.NoInternetDialog$9.hasActiveConnection(NoInternetDialog.java:573)
>                                                                                 at am.appwise.components.ni.Ping.onPostExecute(Ping.java:22)
>                                                                                 at am.appwise.components.ni.Ping.onPostExecute(Ping.java:10)
>                                                                                 at android.os.AsyncTask.finish(AsyncTask.java:632)
>                                                                                 at android.os.AsyncTask.access$600(AsyncTask.java:177)
>                                                                                 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                 at android.os.Looper.loop(Looper.java:136)
>                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5103)
>                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
>                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
>                                                                                 at dalvik.system.NativeStart.main(Native Method)
>                                                                              Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
>                                                                                 at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
>                                                                                 at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
>                                                                                 at android.content.res.Resources.loadDrawable(Resources.java:2132)
>                                                                                 at android.content.res.Resources.getDrawable(Resources.java:715) 
>                                                                                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:353) 
>                                                                                 at am.appwise.components.ni.NoInternetDialog.initButtonStyle(NoInternetDialog.java:275) 
>                                                                                 at am.appwise.components.ni.NoInternetDialog.onCreate(NoInternetDialog.java:195) 
>                                                                                 at android.app.Dialog.dispatchOnCreate(Dialog.java:396) 
>                                                                                 at android.app.Dialog.show(Dialog.java:268) 
>                                                                                 at am.appwise.components.ni.NoInternetDialog.show(NoInternetDialog.java:563) 
>                                                                                 at am.appwise.components.ni.NoInternetDialog$9.hasActiveConnection(NoInternetDialog.java:573) 
>                                                                                 at am.appwise.components.ni.Ping.onPostExecute(Ping.java:22) 
>                                                                                 at am.appwise.components.ni.Ping.onPostExecute(Ping.java:10) 
>                                                                                 at android.os.AsyncTask.finish(AsyncTask.java:632) 
>                                                                                 at android.os.AsyncTask.access$600(AsyncTask.java:177) 
>                                                                                 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645) 
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                 at android.os.Looper.loop(Looper.java:136) 
>                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5103) 
>                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
>                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790) 
>                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606) 
>                                                                                 at dalvik.system.NativeStart.main(Native Method) 
>

**Comment by robertlevonyan** [comment]
Please, update the lib to version 1.1.1
