### ISSUE TITLE
Content is not allowed in prolog Error

### ISSUE THREAD

**Issue by rakshithsj30** [appwise-labs/NoInternetDialog#7]
I got this error. How can i fix it?
C:\Users\Rakshith Shetty\.android\build-cache\acb394dc94c4798ca4e90f1a36706fa85ceb35ae\output\res\font\montserrat_bold.ttf
Error:(1, 1) Error: Content is not allowed in prolog.
Thanks

**Comment by robertlevonyan** [comment]
what is your version of android?

**Comment by rakshithsj30** [comment]
minSdkVersion 16
  targetSdkVersion 26
  compileSdkVersion 26
   Device: Android M
Android Studio Version: 2.3.2

**Comment by robertlevonyan** [comment]
I think this is because of your android studio version. This lib is created on Android Studio 3.0 with Gradle plugin version 3.0. In Android Studio 2.3.. is used an older version of Gradle plugin. Try to upgrade to a newer version
