### ISSUE TITLE
UnregisterReceiver

### ISSUE THREAD

**Issue by shafaque** [appwise-labs/NoInternetDialog#9]
Activity has leaked IntentReceiver am.appwise.components.ni.nointernetdialog.NetworkStatusReceiver@36923f41 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity  has leaked IntentReceiver am.appwise.components.ni.nointernetdialog.NetworkStatusReceiver@36923f41 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:904)

**Comment by shafaque** [comment]
@robertlevonyan Please help

**Comment by robertlevonyan** [comment]
please update to version 1.1.2
